# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @return a random sample of size \code{N}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N) {
    .Call('_StatComp22030_gibbsC', PACKAGE = 'StatComp22030', N)
}

